### ISSUE TITLE
Incorrect gotk_reconcile_condition metric after migration to v0.16.0-rc.3

### ISSUE THREAD

**Issue by renato0307** [flux-iac/tofu-controller#1068] opened 2023-10-26 17:41 UTC
Hi,

I've upgraded from `v0.14.0` to `v0.16.0-rc.3`.

The `gotk_reconcile_condition` for the `Ready` condition is not being correctly reported.
* Terraforms are Ready
* Metric reports Unknown=1 and True/False=0

Do you have any idea the cause? Could you please help me troubleshoot this issue?

Thank you in advance.

More details:

### v0.16.0-rc.3

![image](https://github.com/weaveworks/tf-controller/assets/2320628/5223a555-96d9-45d0-817a-8357fb817970)

![image](https://github.com/weaveworks/tf-controller/assets/2320628/4de00cee-62d8-49ac-a3ec-a4d09dec9fbf)

![image](https://github.com/weaveworks/tf-controller/assets/2320628/2bb6ed6d-0cca-4a02-9efd-d62bf64b375f)

### v0.14.0

![image](https://github.com/weaveworks/tf-controller/assets/2320628/cba2823e-2d7d-4a33-ac95-6dfb095c57f4)

![image](https://github.com/weaveworks/tf-controller/assets/2320628/4a1f812d-9d7f-4f49-9232-c791577cebff)

**Comment by renato0307** [comment] 2023-10-26 18:20
Ran the controller with `log-level=trace`:

![image](https://github.com/weaveworks/tf-controller/assets/2320628/317fb166-3611-406c-94f1-94e5deee3f74)

**Comment by chanwit** [comment] 2023-10-27 05:39
Thank you @renato0307 for reporting this.

Maybe it's because we have recently changed the code base to match that of Flux v2 GA.

@luizbafilho @yitsushi could you help take a look please?

cc @LappleApple

**Comment by renato0307** [comment] 2023-11-09 13:38
Anyone working on this @LappleApple @chanwit? May I give it a go?

**Comment by LappleApple** [comment] 2023-11-09 13:39
Hey @renato0307, all yours. :) I'll assign it to you.

**Comment by yitsushi** [comment] 2023-11-09 13:39
@renato0307 : Go for it, if any of us picked it up, we assign ourselves.

**Comment by renato0307** [comment] 2023-11-09 18:26
Looks like the problem is on the [defer](https://github.com/weaveworks/tf-controller/blob/1958307fc83cc56f486453885e9426cd88f93d80/controllers/tf_controller.go#L133).

The `defer` uses the original [terraform](https://github.com/weaveworks/tf-controller/blob/1958307fc83cc56f486453885e9426cd88f93d80/controllers/tf_controller.go#L126) var which contains the `Unknown` condition.

It is overwriting the metric written [here](https://github.com/weaveworks/tf-controller/blob/1958307fc83cc56f486453885e9426cd88f93d80/controllers/tf_controller.go#L439), using the `reconciledTerraform` var.

**Comment by chanwit** [comment] 2024-03-25 15:29
Thank you for bringing this up @adonispd 
could anyone please help use clarify this bug again?
Happy to help review and land a fix if someone could point things out clearly.

**Comment by TarasLykhenko** [comment] 2024-04-26 15:40
Hi @chanwit,
I could reproduce this issue in the v0.16.0-rc.4.
Wrote a short summary on the PR.

**Closed** 2024-05-04 10:44 UTC
Labels: kind/bug, good first issue, area/observability

**Comment by ricardomiguel-os** [comment] 2024-05-06 15:30
@chanwit any idea when the team will create a new release candidate?
